### ISSUE TITLE
Security Vulnerability

### ISSUE THREAD

**Issue by haby0** [github/ghas-jira-integration#22]
Submit security vulnerabilities to securitylab@github.com?

**Comment by cmboling** [comment]
Hey @haby0! Is this a request for the `ghas-jira-integration`, and if so would you mind clarifying?

**Comment by haby0** [comment]
Yep, there is a small vulnerability in `ghas-jira-integration`

**Comment by cmboling** [comment]
Would you mind emailing me the details? 💯 I'd appreciate it! cmboling@github.com

**Comment by haby0** [comment]
@cmboling Hi, can you disclose this vulnerability and apply for a CVE?

Reference: https://docs.github.com/en/code-security/security-advisories/about-github-security-advisories
