### ISSUE TITLE
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' 

### ISSUE THREAD

**Issue by CyberCowboys** [github/ghas-jira-integration#57]
## Issue Summary 🚨
On October 1st, the `ghas-jira-integration` pipeline failed due to an ImportError linked to the **Werkzeug** package.

## Error Message 🛑
```markdown
ImportError: cannot import name 'url_quote' from 'werkzeug.urls'
```

## Diagnostic Details 
- **Issue Identified:** The problem is related to an upgrade in the Werkzeug package.
  - **Reasoning:** Import statement in code is incompatible with the latest version of Werkzeug.

- **Version Info:**
  - **Working Version:** Werkzeug-2.3.7
  - **Problematic Version:** Werkzeug-3.0.0
  - **How Discovered:** Compared logs from a successful run to a failed run to pinpoint the version discrepancy.

**Comment by marvelous-melanie** [comment]
Flagging that we're also having this issue!

**Comment by leachtucker** [comment]
Us as well.

**Comment by YurisRPadilla** [comment]
Hi there, is someone working on this issue? Or we should fix it ourselves?

**Comment by aibaars** [comment]
@YurisRPadilla @CyberCowboys This problem seems to be caused by old versions of flask using the deprecated `url_quote` function, which was removed from werkzeug. I think #58 which updates flask to version 2.3 should resolve this problem. Could you let me know if #58 fixes the issue for you?

**Comment by marvelous-melanie** [comment]
@aibaars this fix works for me!
